bedroom_choices={
        '1':1,
        '2':2,
        '3':3,
        '4':4,
        '4':4,
        '5':5,


}

price_choices={
    '100':'100',
    '200':'200',
    '300':'300',
    '400':'400',
    '500':'500',
    '600':'600',
    '700000':'7,00000',
    '800000':'8,00000',
    '900000':'1,00000',
    '1000000':'10,00000',
}

state_choices={
'ANP':'Andhra Pradesh',
'ARP':'Arunachal Pradesh',
'AS':'Assam',
'BI':'Bihar',
'CHH':'Chhattisgarh',
'GO':'Goa',
'GU':'Gujarat',
'HR':'Haryana',
'HP':'Himachal Pradesh',
'J&K':'Jammu & Kashmir',
'JH':'Jharkhand',
'KA':'Karnataka',
'KE':'Kerala',
'MP':'Madhya Pradesh',
'MA':'Maharashtra',
'MI':'Manipur',
'ME':'Meghalaya',
'MZ':'Mizoram',
'NA':'Nagaland',
'OD':'Odisha',
'PU':'Punjab',
'RA':'Rajasthan',
'SI':'Sikkim',
'TN':'Tamil Nadu',
'TE':'Telangana',
'TR':'Tripura',
'UP':'Uttar Pradesh',
'UK':'Uttarakhand',
'WB': 'West Bengal',
'ANI':'Andaman and Nicobar Islands',
'CH':'Chandigarh',
'DNH':'Dadra and Nagar Haveli',
'DD':'Daman and Diu',
'LD':'Lakshadweep',
'Delhi':'Delhi',
'PC':'Puducherry',
}
